plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(":ryzen-framework:ryzen-framework-service")

    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    implementation 'org.springframework.cloud:spring-cloud-starter-consul-config'
    implementation 'org.springframework.cloud:spring-cloud-starter-consul-discovery'

    implementation 'org.postgresql:postgresql'
    implementation libs.mybatis.plus.spring
    implementation libs.mybatis.plus.join
    implementation libs.springdoc.openapi
}
