plugins {
    id 'org.springframework.boot' version '4.1.1' apply false
    id 'io.spring.dependency-management' version '1.1.7' apply false
}

allprojects {
    group = 'com.qianjh'
    version = '1.0.0'

    repositories {
        mavenLocal()

        maven {
            url = 'https://maven.aliyun.com/repository/public'
        }
    }
}

subprojects {
    apply plugin: 'idea'

    if (file('src/main/java').exists()) {
        apply plugin: 'java-library'
        apply plugin: 'io.spring.dependency-management'

        java {
            toolchain {
                languageVersion = JavaLanguageVersion.of(21)
            }
        }

        configurations {
            compileOnly {
                extendsFrom annotationProcessor
            }
        }

        dependencyManagement {
            imports {
                mavenBom "org.springframework.boot:spring-boot-dependencies:${libs.versions.spring.boot.get()}"
                mavenBom "org.springframework.cloud:spring-cloud-dependencies:${libs.versions.spring.cloud.get()}"
            }
        }

        dependencies {
            compileOnly libs.lombok
            annotationProcessor libs.lombok
        }

        clean {
            def logsDir = layout.projectDirectory.dir('logs')

            delete logsDir

            doFirst {
                println "DELETE ${logsDir.asFile}"
            }
        }

        test {
            useJUnitPlatform()
        }
    }

}

