rootProject.name = 'ryzen'
// framework
include 'ryzen-framework:ryzen-framework-common'
include 'ryzen-framework:ryzen-framework-gateway'
include 'ryzen-framework:ryzen-framework-http'
include 'ryzen-framework:ryzen-framework-security'
include 'ryzen-framework:ryzen-framework-service'
include 'ryzen-framework:ryzen-framework-servlet'
include 'ryzen-framework:ryzen-framework-stream'
include 'ryzen-framework:ryzen-framework-token'
include 'ryzen-framework:ryzen-framework-websocket'
// plugin
include 'ryzen-plugin:ryzen-plugin-aliyun'
include 'ryzen-plugin:ryzen-plugin-aliyun-oss'
include 'ryzen-plugin:ryzen-plugin-oss'
// model
include 'ryzen-model:ryzen-model-framework'
include 'ryzen-model:ryzen-model-tenant'
// gateway (port:70XX)
include 'ryzen-gateway:ryzen-gateway-oem'
include 'ryzen-gateway:ryzen-gateway-open'
include 'ryzen-gateway:ryzen-gateway-partner'
include 'ryzen-gateway:ryzen-gateway-saas'
include 'ryzen-gateway:ryzen-gateway-tenant'
include 'ryzen-gateway:ryzen-gateway-user'

// service (port:80XX)
include 'ryzen-service:ryzen-service-oem'
include 'ryzen-service:ryzen-service-saas'
include 'ryzen-service:ryzen-service-tenant'
include 'ryzen-service:ryzen-service-user'

// websocket (port:81XX)

// stream (port:82XX)

// job (port:83XX)
include 'ryzen-job:ryzen-job-outbox'