rootProject.name = 'ryzen'
include 'ryzen-framework:ryzen-framework-common'
include 'ryzen-framework:ryzen-framework-crypto'
include 'ryzen-framework:ryzen-framework-servlet'
include 'ryzen-framework:ryzen-framework-stream'
include 'ryzen-framework:ryzen-framework-tenant'

include 'ryzen-gateway-partner'
include 'ryzen-framework:ryzen-framework-token'