rootProject.name = 'ryzen'
// framework
include 'ryzen-framework:ryzen-framework-common'
include 'ryzen-framework:ryzen-framework-gateway'
include 'ryzen-framework:ryzen-framework-http'
include 'ryzen-framework:ryzen-framework-security'
include 'ryzen-framework:ryzen-framework-service'
include 'ryzen-framework:ryzen-framework-servlet'
include 'ryzen-framework:ryzen-framework-stream'
include 'ryzen-framework:ryzen-framework-token'
include 'ryzen-framework:ryzen-framework-websocket'
// plugin
include 'ryzen-plugin:ryzen-plugin-aliyun'
include 'ryzen-plugin:ryzen-plugin-aliyun-oss'
include 'ryzen-plugin:ryzen-plugin-oss'
include 'ryzen-plugin:ryzen-plugin-sms'
// model
include 'ryzen-model:ryzen-model-framework'
include 'ryzen-model:ryzen-model-tenant'
include 'ryzen-model:ryzen-model-user'
// gateway (port:70XX)
//include 'ryzen-gateway:ryzen-gateway-oem-app'
include 'ryzen-gateway:ryzen-gateway-partner'
//include 'ryzen-gateway:ryzen-gateway-saas-app'
include 'ryzen-gateway:ryzen-gateway-tenant-app'
include 'ryzen-gateway:ryzen-gateway-user-app'
include 'ryzen-gateway:ryzen-gateway-user-open'

// service (port:80XX)
//include 'ryzen-service:ryzen-service-oem'
//include 'ryzen-service:ryzen-service-saas'
include 'ryzen-service:ryzen-service-stream'
include 'ryzen-service:ryzen-service-tenant'
include 'ryzen-service:ryzen-service-user'

// websocket (port:81XX)

// stream (port:82XX)