server:
  port: 7001

spring:
  application:
    name: ryzen-gateway-tenant
  profiles:
    active: dev
  config:
    import: optional:consul:192.168.187.1:8500
  output:
    ansi:
      enabled: detect
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${ryzen.mysql.default.host}/${ryzen.mysql.default.schema}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${ryzen.mysql.default.username}
    password: ${ryzen.mysql.default.password}
  data:
    redis:
      host: ${ryzen.redis.default.host}
      port: ${ryzen.redis.default.port}
      password: ${ryzen.redis.default.password}
  cloud:
    inetutils:
      preferred-networks: 10.168
    loadbalancer:
      cache:
        ttl: 5s
    consul:
      discovery:
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
        service-name: ${spring.application.name}
        prefer-ip-address: true
      config:
        prefixes: config
        default-context: application
        data-key: data
        format: yaml
        watch:
          enabled: false # https://github.com/spring-cloud/spring-cloud-consul/issues/951
          delay: 3000
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
          filter:
            request-rate-limiter:
              enabled: true
          loadbalancer:
            use404: true
          metrics:
            enabled: true
          httpclient:
            connect-timeout: 3000
            response-timeout: 30000
          routes:
            # ----------------------------------------------------------------------
            - id: tenant
              order: 3
              metadata:
                remarks: tenant
              predicates:
                - Path=/tenant/**
              filters:
                - StripPrefix=1
                - PrefixPath=/tenant
              uri: lb://ryzen-service-tenant
            # ----------------------------------------------------------------------
            - id: user
              order: 3
              metadata:
                remarks: user
              predicates:
                - Path=/user/**
              filters:
                - StripPrefix=1
                - PrefixPath=/tenant
              uri: lb://ryzen-service-user