plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(":ryzen-framework:ryzen-framework-gateway")
    implementation project(":ryzen-framework:ryzen-framework-token")
    implementation project(":ryzen-framework:ryzen-framework-security")

    implementation project(":ryzen-model:ryzen-model-framework")

    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis-reactive'

    implementation 'org.springframework.cloud:spring-cloud-starter-consul-config'
    implementation 'org.springframework.cloud:spring-cloud-starter-consul-discovery'

//    implementation 'org.postgresql:postgresql'
    implementation 'com.mysql:mysql-connector-j'
    implementation libs.mybatis.plus.spring
}
