management:
  endpoints:
    access:
      default: none
    web:
      exposure:
        include: health
  endpoint:
    health:
      access: unrestricted

pgsql:
  default:
    host: pgm-uf6d8e14v487n63m.pg.rds.aliyuncs.com
    schema: ryzen_dev
    username: username
    password: dev@do6VQOh2gmh1EW9mjQx5sv0XEyvq

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true