server:
  port: 8001

spring:
  application:
    name: ryzen-service-oem-tenant-admin
  config:
    import: optional:consul:192.168.187.1:8500
  profiles:
    active: dev
  cloud:
    inetutils:
      preferred-networks: 10.8
    consul:
#      host: 192.168.187.1
#      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
        service-name: ${spring.application.name}
        prefer-ip-address: true
      config:
        prefixes: config
        default-context: application
        format: yaml
  output:
    ansi:
      enabled: detect
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${pgsql.default.host}/${pgsql.default.schema:ryzen}
    username: ${pgsql.default.username}
    password: ${pgsql.default.password}
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  group-configs:
    - group: 'admin'
      display-name: '管理员'
      paths-to-match:
        - '/admin/**'
    - group: 'admin-oem'
      display-name: 'OEM管理员'
      paths-to-match:
        - '/admin-oem/**'
    - group: 'admin-tenant'
      display-name: '租户管理员'
      paths-to-match:
        - '/admin-tenant/**'
    - group: 'cli'
      display-name: '命令行'
      paths-to-match:
        - '/cli/**'
    - group: 'partner'
      display-name: '合作方'
      paths-to-match:
        - '/partner/**'